version: "3"

services:
  webservicephp:
    image: "webservicephp:1.0"
    expose:
      - "80"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webservicephp
    ports:
      - "8080:8080"
